defaults: &defaults
  adapter: postgresql
  encoding: utf8
  database: tasks_ember_development
  pool: 5
  timeout: 5000
  host: localhost

development:
  <<: *defaults

test:
  <<: *defaults
  database: tasks_ember_test
